### ISSUE TITLE
Possible support for MSSQL 2005 and 2008?

### ISSUE THREAD

**Issue by gladstoneg** [polyjdbc/polyjdbc#19]
Currently, org.polyjdbc.core.dialect.MsSqlDialect returns true for supportsSequences().

However, sequences have been introduced with MSSQL 2012 (see http://technet.microsoft.com/en-us/library/ff877934.aspx). Is there a possibility to support older MSSQL Servers (2005 and 2008) that don't recognize the SEQUENCE keyword?

I've got an exception when a framework using polyjdbc tries to create a sequence for a pk column:
`Exception in thread "main" org.polyjdbc.core.exception.SchemaManagerException: [DDL_ERROR] Failed to run DDL:
CREATE SEQUENCE jv_commit_pk_seq START WITH 1 INCREMENT BY 1
at org.polyjdbc.core.schema.SchemaManagerImpl.ddl(SchemaManagerImpl.java:91)
	at org.polyjdbc.core.schema.SchemaManagerImpl.create(SchemaManagerImpl.java:52)
	at org.javers.repository.sql.schema.JaversSchemaManager.ensureTable(JaversSchemaManager.java:222)
	at org.javers.repository.sql.schema.JaversSchemaManager.ensureSchema(JaversSchemaManager.java:41)
	at org.javers.repository.sql.JaversSqlRepository.ensureSchema(JaversSqlRepository.java:80)
	at org.javers.core.JaversBuilder.build(JaversBuilder.java:105)`

`Caused by: java.sql.SQLException: Unknown object type 'SEQUENCE' used in a CREATE, DROP, or ALTER statement.
	at net.sourceforge.jtds.jdbc.SQLDiagnostic.addDiagnostic(SQLDiagnostic.java:372)
	at net.sourceforge.jtds.jdbc.TdsCore.tdsErrorToken(TdsCore.java:2988)
	at net.sourceforge.jtds.jdbc.TdsCore.nextToken(TdsCore.java:2421)
	at net.sourceforge.jtds.jdbc.TdsCore.getMoreResults(TdsCore.java:671)
	at net.sourceforge.jtds.jdbc.JtdsStatement.processResults(JtdsStatement.java:613)
	at net.sourceforge.jtds.jdbc.JtdsStatement.executeSQL(JtdsStatement.java:572)
	at net.sourceforge.jtds.jdbc.JtdsStatement.executeImpl(JtdsStatement.java:809)
	at net.sourceforge.jtds.jdbc.JtdsStatement.execute(JtdsStatement.java:1282)
	at org.polyjdbc.core.schema.SchemaManagerImpl.ddl(SchemaManagerImpl.java:88)
	... 7 more`

**Comment by bartoszwalacik** [comment]
I dont think so, we don't have Windows here so developing anything for MSSQL Servers is a pain, especially for legacy versions.
